//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoockieByLogin
    {
        public int CoockieId { get; set; }
        public int UserId { get; set; }
        public string Coockie { get; set; }
    
        public virtual User User { get; set; }
    }
}
