//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Category1 = new HashSet<Category>();
        }
    
        public int TaskId { get; set; }
        public int UserId { get; set; }
        public string TaskName { get; set; }
        public int PriorityId { get; set; }
        public string FullDescription { get; set; }
        public System.DateTime SetDate { get; set; }
        public int IsPerformance { get; set; }
        public Nullable<System.TimeSpan> SpendTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Category Category { get; set; }
        public virtual Priority Priority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category1 { get; set; }
    }
}
